### ISSUE TITLE
NameError with Cancellable coroutines

### ISSUE THREAD

**Issue by stlehmann** [peterhinch/micropython-async#20]
I'm using Cancellable coroutines to display the duration of a process via serial connection. the following code works fine when called for the first time. 

    async def measure_dose_time(*args: Any, **kwargs: Any) -> None:
        """Measure the current dose time and send to host."""
        t0 = utime.ticks_ms()

        while True:
            await asyncio.sleep(1)
            t1 = utime.ticks_ms()
            dose_time_s = t1 - t0
            await ser.send_msg_async(
                json.dumps({"type": "dose_time", "seconds": dose_time_s}) + "\n"
            )

    async def dose() -> None:
        """Handle automatic trigger signal."""
        loop.create_task(asyn.Cancellable(measure_dose_time)())
        asyncio.sleep(5)
        await asyn.Cancellable.cancel_all()

When calling the code a second time I get the following error message.

    Traceback (most recent call last):
      File "main.py", line 16, in <module>
      File "meter.py", line 236, in <module>
      File "uasyncio/core.py", line 146, in run_forever
      File "uasyncio/core.py", line 101, in run_forever
      File "meter.py", line 168, in dose
      File "asyn.py", line 268, in cancel_all
      File "asyn.py", line 260, in _cancel
      File "uasyncio/core.py", line 239, in cancel
    NameError: local variable referenced before assignment
    MicroPython v1.9.3-240-ga275cb0f on 2018-01-26; PYBv1.1 with STM32F405RG
    Type "help()" for more information.

I looked up the code in core.py but can not explain why this error occurs. Do you have any suggestions?

**Comment by stlehmann** [comment]
Arghh, I found the problem. I need to decorate the *Cancellable* coroutine with the `cancellable` decorator like this:

    @asyn.cancellable
    async def measure_dose_time(*args: Any, **kwargs: Any) -> None:
        """Measure the current dose time and send to host."""
        t0 = utime.ticks_ms()
        ...

Now it works just fine. Thanks for this great library ;)
